### ISSUE TITLE
Converting circular structure in JSON (TypeError in Social Media)

### ISSUE THREAD

**Issue by b0llu** [neogcamp/mockBee#108] opened 2022-04-25 15:21 UTC
**Describe the bug**
The bug occurs when we try to like and bookmark same post of a user at same time. If we try to call the same api again of bookmark or like we counter 400 error saying its already bookmarked or can not dislike post below 0.

**To Reproduce**

1. Try to like any post
2. Try to bookmark the same liked post
3. See error in console as "converting circular structure in JSON"

**Expected behavior**
It is expected to like and bookmark the same post and return the respected output

**Screenshots**
![image](https://user-images.githubusercontent.com/89966036/165120148-9893b322-3d25-405d-9613-8e29105288b5.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: chrome

**Additional context**
Was able to get around the bug by adding 
current (```"user.bookmarks.push(post);"```)
what I changed (```"user.bookmarks.push(JSON.parse(JSON.stringify(post)));"``` )
on line number #134 of userController.js of Social Media

**Comment by himadri2110** [comment] 2022-05-10 11:27
I was stuck at the same place and your fix worked. Thanks, @b0llu

**Comment by himadri2110** [comment] 2022-05-10 11:28
> **Describe the bug** The bug occurs when we try to like and bookmark same post of a user at same time. If we try to call the same api again of bookmark or like we counter 400 error saying its already bookmarked or can not dislike post below 0.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Try to like any post
> 2. Try to bookmark the same liked post
> 3. See error in console as "converting circular structure in JSON"
> 
> **Expected behavior** It is expected to like and bookmark the same post and return the respected output
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/89966036/165120148-9893b322-3d25-405d-9613-8e29105288b5.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10
> * Browser: chrome
> 
> **Additional context** Was able to get around the bug by adding current (`"user.bookmarks.push(post);"`) what I changed (`"user.bookmarks.push(JSON.parse(JSON.stringify(post)));"` ) on line number #134 of userController.js of Social Media

I was stuck at the same place and your fix worked. Thanks, @b0llu

**Comment by himadri2110** [comment] 2022-05-10 11:28
I was stuck at the same place and your fix worked. Thanks, @b0llu

**Comment by romabulani** [comment] 2022-05-11 11:56
> JSON.parse(JSON.stringify(post))

I was also stuck at the same place. Thankyou @b0llu

**Comment by hsnice16** [comment] 2022-05-15 19:30
I was also facing this same issue, and first tried the workaround that @b0llu has suggested then it was not giving the error, but it was not working as intended. 

When I was liking a post first and then bookmarking the same post and after bookmarking, I was changing the tab to see all the bookmarks it was showing both the things correctly (liked and bookmarked) 
But, when I was bookmarking the post first and then liking it and then changing the tab to see all the bookmarks it was not showing that the post has been liked.
Though it was showing the liked thing on home.

On home, I am fetching the posts using the all posts public API.
On bookmark, I am fetching the posts using the all bookmarks private API.

How I found workaround of this,
In `PostController.js` instead of pushing the whole `user` object in `likedBy` and `dislikedBy`, I am only pushing the `users` id and username.
Something like,
```js
post.likes.likedBy.push({ _id: user._id, username: user.username });
post.likes.dislikedBy.push({ _id: user._id, username: user.username });
```

And, I also think that pushing the whole `user` object was the issue of the above bug. As the `bookmarks` property of the `user` object is containing the `post` which has the `likes` object. And this was making the circular structure.

**Comment by Hamza-777** [comment] 2022-05-16 03:05
@hsnice16 Your way works but if you just do the following then it works as well:
`
post.likes.likedBy.push({ ...user, bookmarks: [] });
post.likes.dislikedBy.push({ ...user, bookmarks: [] });
`

**Comment by hsnice16** [comment] 2022-05-16 04:30
@Hamza-777 Yup! this will work also. But I think, this is not the right way, as you are giving a false impression that there are no bookmarks the user has, but it may has some bookmarks.

But this will solve the problem of Circular structure, as I explained above also that because of `bookmarks` it is showing this error.

**Comment by Hamza-777** [comment] 2022-06-17 06:46
@sohamsshah this issue is resolved you can close it now!

**Closed** 2022-06-17 07:51 UTC
